version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_vue_nginx
    working_dir: /var/www/html
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./.docker/server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - network

  php:
    build:
      context: ./.docker/php
    container_name: laravel_vue_php
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    networks:
      - network

  mysql:
    image: mysql:5.7.22
    container_name: laravel_vue_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 4306:3306
    volumes:
      - ./.docker/.database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_vue_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    links:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - network

  yarn:
    image: node:latest
    container_name: laravel_vue_yarn
    working_dir: /var/www/html
    entrypoint: ['yarn']
    volumes:
      - ./:/var/www/html
    networks:
      - network

networks:
  network:
